### ISSUE TITLE
Optionally ignore certificate errors

### ISSUE THREAD

**Issue by hakan42** [buzz/ics2owncloud.py#16]
The certificate of a server can be either expired (the letsencrypt scripts did not run for a time 😈 ) or can be issued via an company internal certificate authority.

In any case, it might be helpful to have a way to ignore certificate validation errors.

Also mentioned in #5

**Comment by hakan42** [comment]
Pull Request #17 is available.

**Comment by buzz** [comment]
I think it's crucial that you understand the importance of certificate validation. If you disable it you're actually creating a security hole!

The only use case I can think of would be during development. But during development you could easily put a `validate=False` to your code, right?

> The certificate of a server can be either expired

Certificates expire for a reason. Fix your certificate!

> or can be issued via an company internal certificate authority

If your CA is not in the Mozilla trust store (this is what the Requests library actually uses) because it's self-signed or not yet accepted by Mozilla you can still make Requests trust your CA:
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification
